Add fragments
corinaorasan171015/AppNavigation pull request #1
Opened 2021-02-15 09:33 UTC by corinaorasan171015

2021-02-16 15:00 UTC, deniscoman requested changes

2021-02-16 15:00 UTC, deniscoman commented on app/build.gradle
> +    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
Extract version number in a variable like we have on the other libraries

2021-02-16 15:00 UTC, deniscoman commented on app/src/main/java/com/example/android/navigation/GameFragment.kt
> +                changeAnswerIndex(checkedId)
We should have a better name for this function.

2021-02-22 09:37 UTC, AlexandraDamaschin commented on gradle/wrapper/gradle-wrapper.properties
> +#Mon Feb 15 10:58:12 EET 2021
We should not track this changes on Git as they are irrelevant for code reviews

2021-02-22 09:40 UTC, AlexandraDamaschin commented
Learn more about squash and apply them to this PR as you have loads of duplicated commits with the same message: 
![image](https://user-images.githubusercontent.com/29914519/108690042-8a8fdb00-7502-11eb-928f-ae9fa262026a.png)

2021-02-22 09:41 UTC, AlexandraDamaschin requested changes
Apply git changes to make your pr nicer.

2021-02-22 12:42 UTC, AlexandraDamaschin approved these changes

2021-02-22 12:55 UTC, merged